name = "r2-uploader-example-worker"
compatibility_date = "2023-12-01"
main = "src/index.ts"

# modify `bucket_name`
# don't modify the `binding`
r2_buckets = [
    {binding = "R2_BUCKET", bucket_name = "test"}
]

[[kv_namespaces]]
binding = "UPLOAD_SIZES"
id = "1001"

[[ratelimits]]
name = "UPLOAD_LIMITER"
namespace_id = "1002"
simple = { limit = 100, period = 60 }

[[ratelimits]]
name = "READ_LIMITER"
namespace_id = "1003"
simple = { limit = 500, period = 60 }
